#-------------------------------------------------------------------------------
# Copyright (c) 2019 RWTH Aachen University, Germany,
# Virtual Reality & Immersive Visualisation Group.
#-------------------------------------------------------------------------------

#The include file can be change to either be removed or reference a specific commit.
#Reference the Gitlab CI website for this

include:
  - project: 'vr-group/unreal-development/unreal-ci'
    ref: master 
    file: '/shared_scripts.yml'
    
#In this file you are able to configure your pipeline.
#If you want to use the standard pipeline with all steps and deployment mechanisms, you are set-up correctly now.
#If you want to customize something, either overwrite things that are defined in the shared_scripts repository,
#or remove the "extends" and write your own scripts
#
#If you want your pipeline to run on every commit, just remove the "only" blocks. Keep in mind, that a build
#can take some time.
#
#If you want to alter the unreal-building process two variables are defined for either changing the CLIENT_CONFIG or
#for adding EXTRA_ARGS to the building process

stages:
  - build
  - deploy

Build_Windows:
    only: ['web', 'schedules']
    extends: .Build_Windows_
    tags:
        - windows
        - unreal-4.22
    # variables:
       # CLIENT_CONFIG: "DebugGame"
    
Build_CentOS:
    only: ['web', 'schedules']
    extends: .Build_CentOS_
    tags:
        - centos
        - unreal-4.22
    # variables:
        # CLIENT_CONFIG: "DebugGame"
 
Deploy_CAVE:
    only: ['web', 'schedules']
    extends: .Deploy_CAVE_
    dependencies:
        - Build_CentOS
        
Deploy_Windows:
    only: ['web', 'schedules']
    extends: .Deploy_VRDev_
    dependencies:
        - Build_Windows

 